#######################################
# Home-Assistant-Configuration
# https://github.com/genestealer/Home-Assistant-Configuration
# See Readme for info: https://github.com/genestealer/Home-Assistant-Configuration/blob/master/README.md
#######################################

############################################################
#
# Homeassistant Configuration
#
############################################################
homeassistant:
  # Customization file
  customize: !include customize.yaml
  #Unhide the push notifcation slider https://github.com/home-assistant/home-assistant/issues/16043
  auth_providers:
    - type: homeassistant
  # whitelist_external_dirs:
  #   - /www
  #   - /tmp
  packages: !include_dir_named packages/

############################################################
#
# Standard Configuration Elements
#
############################################################

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# https://github.com/thomasloven/hass-browser_mod
browser_mod:

# https://github.com/thomasloven/hass-lovelace_gen
lovelace_gen:

lovelace:
  mode: storage
  resources:
    #=== FONTS
    - url: https://fonts.googleapis.com/css?family=Oswald
      type: css
    - url: https://fonts.googleapis.com/css?family=Dosis
      type: css
  # Add yaml dashboards
  dashboards:
    lovelace-garden: #https://github.com/kloggy/HA-Irrigation-Version2/
      mode: yaml
      title: Garden
      icon: mdi:flower
      show_in_sidebar: true
      filename: myirrigation.yaml
# Enables configuration UI
config:

#Home Assistant Cloud - NOPE!
cloud:

# Enable web interface
http:
  #  api_password: !secret http_password
  server_port: 8123
  # SSL is now performed by reverse proxy
  #  ssl_certificate: !secret SSL_cert
  #  ssl_key: !secret SSL_key
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200 # Add the IP address of the proxy server
    - 172.30.33.0/24 # You may also provide the subnet mask
    # - 192.168.10.21/24 # IP Reverse_Proxy Nginx Proxy Manager
  ip_ban_enabled: true
  login_attempts_threshold: 20

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time. (Cleared at startup)
history:

# Tracked history. Dependency of the history integration
recorder:
  purge_keep_days: 64
  exclude:
    # domains:
    #   - automation
    #   - updater
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.time_date
      - sensor.time_utc
      - sensor.date_time_iso
      - sensor.internet_time
    entity_globs: input_number.irrigation* #https://github.com/kloggy/HA-Irrigation-Version2/blob/master/Pre-Requisites.md

# View all events in a logbook. Depends on the recorder integration for storing the data.
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.time_date
      - sensor.time_utc
      - sensor.date_time_iso
      - sensor.internet_time
      - sensor.server_server_health
      - sensor.unscaled_house_consumption_current
      - sensor.server_server_power_on_time
      - sensor.cc_cpu_temperature
      - sensor.cc_cpu_load
    entity_globs:
      - sensor.adguard_*
      - sensor.*_last_seen
      - sensor.*_retries

# Enables a map showing the location of tracked devices
map:

# https://github.com/home-assistant/home-assistant/issues/1806
logger:
  default: error
  logs:
    requests.packages.urllib3.connectionpool: critical
    rflink.protocol: error #fatal
    homeassistant.components.sensor.plex: fatal
    urllib3.connectionpool: error
    homeassistant.components.recorder: fatal
    # axis: debug
    # homeassistant.components.axis: debug
    homeassistant.components.rest: debug

# System Health integration
system_health:

# Meta-component integration
default_config:

# My Home Assistant integration https://www.home-assistant.io/integrations/my
# Needed for 2023 Nest
my:

# Media source integration platform allows integrations to expose media for use inside Home Assistant through the Media Browser panel or
# through supported media players like Google Cast.
media_source:

############################################################
#
# Components
#
############################################################

# Track the sun.
sun:
  # elevation: !secret elevation

#################################################
# Text to speech.
tts:
  - platform: google_translate
    service_name: google_translate_say

#################################################
# Use external MQTT broker.
mqtt:
  binary_sensor: !include_dir_merge_list includes/mqtt/binary_sensors/
  cover: !include_dir_merge_list includes/mqtt/covers/
  sensor: !include_dir_merge_list includes/mqtt/sensors/
  switch: !include_dir_merge_list includes/mqtt/switches/
  light: !include_dir_merge_list includes/mqtt/lights/

#################################################
# Push notification providers.
notify:
  - name: Google Cloud Notify
    platform: html5
    # gcm_api_key: !secret gcmKey
    # gcm_sender_id: !secret gcmID
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

#################################################
# Device trackers.
device_tracker:
  # - platform: owntracks
  #   max_gps_accuracy: 250

  - platform: google_maps # Elements per day’ to a limit of 645.
    username: !secret google_maps_username
  # - platform: google_maps # Elements per day’ to a limit of 645.
  #   username: !secret google_maps_username2 # Removed second account, due to moving to using the HA Android App
  # Example configuration.yaml entry

# password: !secret google_maps_password
# - platform: googlehome
#   host: !secret google_home_hub_ip

# - platform: ping
#   hosts:
#     hostone: 192.168.1.16
# - platform: snmp
#   host: 192.168.1.1
#   community: public
#   baseoid: 1.3.6.1.2.1.2.2

# RFLink gateway integration, via ethernet bridge.
#     Try socat pty,link=/config/serialport-rflink,echo=0 tcp:x.x.x.x:xxxx,forever,reuseaddr,keepalive,keepidle=10,keepintvl=10,keepcnt=2
#       https://github.com/home-assistant/core/issues/23577
#         Will not work, as socat is not in HASSIO!

#################################################
rflink:
  host: !secret RF_Link_IP
  port: !secret RF_Link_Port
  wait_for_ack: true
  reconnect_interval: 10 # seconds
  tcp_keepalive_idle_timer: 600 # seconds
  # ignore_devices:
  # - owl_cm113_ead1_current3
  # - owl_cm113_ead1_current1
  # - ev1527_*
  # - wh3_*
  # - wt122*
  # # - sensor.owl_cm113_ea7f_current2
  # # - sensor.owl_cm113_ea7f_current3
  # # - sensor.owl_cm113_ea9f_current2
  # # - sensor.owl_cm113_ea9f_current3
  # # - sensor.owl_cm130_007f_kwatt

  # - sensor.v2phoenix_*
  # - light.drayton_*
  # - light.elrodb_*
  # - light.mertik_*
  # - light.drayton_*
  # - light.btf_*
  # - light.v2phoenix*

# Define values that can be controlled via the frontend and can be used within conditions of automation
# Needed for kloggy/HA-Irrigation-Version2 https://github.com/kloggy/HA-Irrigation-Version2/blob/master/Pre-Requisites.md
input_text:
  notifications_user1_name:
    min: 0
    max: 20
  notifications_user2_name:
    min: 0
    max: 20

#################################################
# Google Assistant intergration.
# Every now and again have to visit this link and lick TEST: https://console.actions.google.com/project/hassio-214617/accountlinking/
google_assistant:
  project_id: !secret google_assistant_project_id
  # api_key: !secret google_assistant_api_key # deprecated and will be removed in 0.105
  service_account: !include private/report_state Home Assistant hassio-214617-7388b38a261c.json
  report_state: true
  # expose_by_default: true # Expose devices in all supported domains by default. If exposed_domains domains is set, only those domains are exposed by default.
  # exposed_domains: # This has no effect if expose_by_default is set to false.
  #   - alarm_control_panel
  #   - switch
  #   # - input_boolean
  #   # - input_select
  #   - fan
  #   - light
  #   - lock
  #   - cover
  #   - camera
  #   - script
  #   - scene
  #   - sensor
  #   # - humidifier
  #   # - vacuum
  #   # - media_player
  #   - climate
  #   # - group

  entity_config:
    switch.adguard_parental_control:
      expose: false
    switch.adguard_safe_browsing:
      expose: false
    switch.adguard_safe_search:
      expose: false
    cover.raw_office_blinds_open_command:
      expose: false
    cover.raw_office_blinds_close_command:
      expose: false
    # script.bedroom_lights_night_mode:
    #   expose: true
    # script.front_garden_lawn_irrigation_timer:
    #   expose: true
    # script.front_garden_pot_irrigation_timer:
    #   expose: true
    # script.back_garden_irrigation_timer:
    #   expose: true
    # script.back_garden_lawn_irrigation_timer:
    #   expose: true
    # climate.entryway:
    #   expose: false

    # group.all_automations:
    #   expose: false # Hide this to avoid telling Google Assistant to shut down everything, it disabling all automations.
    # group.all_covers:
    #   expose: false
    # group.all_lights:
    #   expose: false
    # group.all_switchs:
    #   expose: false
    # group.all_scripts:
    #   expose: false
    # group.automation_system_view:
    #   expose: false
    # group.bathroom_towel_rail_group:
    #   expose: false
    # group.bathroom_view:
    #   expose: false
    # group.bedroom_guest:
    #   expose: false
    # group.bedroom_master:
    #   expose: false
    # group.bunny_shed_controller_info_group:
    #   expose: false
    # group.bunny_shed_group:
    #   expose: false
    # group.bunny_shed_settings:
    #   expose: false
    # group.bunny_shed_view:
    #   expose: false
    # group.rf_link_group:
    #   expose: false
    # # group.server_ilo_status_group:
    # #   expose: false
    # group.groups:
    #   expose: false
    # group.media_players:
    #   expose: false
    # group.media_player:
    #   expose: false

    # switch.adguard_filtering:
    #   expose: false

#################################################
# Proxy video live streams through Home Assistant
stream:
  # ll_hls: true
  # part_duration: 1.5
  # segment_duration: 10

# utility_meter:
#   energy_cumulative_month:
#     source: sensor.esp_doorbell_elec_mon_house_power_meter
#     cycle: monthly
#     # tariffs:
#     #   -
#   energy_cumulative_daily:
#     source: sensor.esp_doorbell_elec_mon_house_power_meter
#     cycle: daily

# # https://github.com/bramstroker/homeassistant-powercalc
# powercalc:
#   scan_interval: 00:01:00 #Each minute
#   power_sensor_naming: "{} Powersensor"
#   create_energy_sensors: false

############################################################
#
# Includes
# Merge named https://home-assistant.io/docs/configuration/splitting_configuration/
#
############################################################

# Single Files
zone: !include includes/zone.yaml
shell_command: !include includes/shell_commands.yaml
automation: !include automations.yaml # Cannot change location or filename as the automations editors only creates here!
script: !include scripts.yaml

# Merge List
# automation old: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensors
light: !include_dir_merge_list includes/lights
binary_sensor: !include_dir_merge_list includes/binary_sensors
switch: !include_dir_merge_list includes/switch
cover: !include_dir_merge_list includes/cover
# camera: !include_dir_merge_list includes/cameras
template: !include_dir_merge_list includes/template

# Merge named dir
# script: !include_dir_merge_named includes/scripts
input_boolean: !include_dir_merge_named includes/input_boolean
input_select: !include_dir_merge_named includes/input_select
input_number: !include_dir_merge_named includes/input_number
rest_command: !include_dir_merge_named includes/rest_commands

# Merge Named
group: !include includes/groups.yaml

# https://www.home-assistant.io/integrations/alert/
alert: !include includes/alert.yaml

scene: !include scenes.yaml
