#***************************************************
# Ice Maker Controller
####################################################
# Config Header for Device
####################################################
substitutions:
  # Used by ESP Home
  device_name: halloween-spider-drop
  # Used by ESP Home
  device_description: "Halloween Spider Drop"
  # Prefix used by Wifi IP, RSSI etc
  upper_devicename: "Halloween Spider Drop"
  # Prefix used by main Inputs & Outputs
  short_devicename: "Spider Drop"
  ip: 192.168.2.47
  pass: "hxN#^fPPv5ZRy%7l"
  status_led: LED_RED
  platform: ESP8266
  board: huzzah

####################################################
# Shared code from all my projects
####################################################
esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ${platform}
  board: ${board}

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: $ip
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    
logger: # Enable logging

api: # Enable Home Assistant API
  password: $pass

ota: # Enable over the air updates
  password: $pass
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  
status_led:
  pin:
    number: ${status_led}
    # inverted: True # To save power with using a coil relay

####################################################
# Non-Shared Code (May contain shared code)
####################################################  
binary_sensor:
# Shared code beginning... 
  # Device avaliablity
  - platform: status  
    name: ${upper_devicename} Status
    device_class: connectivity
# ...shared code end

# switch:
#   - platform: gpio
#     pin:
#       number: GPIO12
#       mode: OUTPUT
#     id: ICE_MAKER_SWITCH
#     restore_mode: RESTORE_DEFAULT_ON  
#     name: "Ice Maker Switch"



   
text_sensor:
# Shared code beginning... 
  # Wifi Data
  - platform: wifi_info  
    ip_address:
      name: ${upper_devicename} IP
      icon: "mdi:ip-network-outline"
    ssid:
      name: ${upper_devicename} SSID
      icon: "mdi:help-network-outline"
    bssid:
      name: ${upper_devicename} BSSID
      icon: "mdi:access-point-network"
# ...shared code end

sensor:
# Shared code beginning... 
  # Wifi signal strength
  - platform: wifi_signal
    name: ${upper_devicename} RSSI
    update_interval: 300s
    # icon: "mdi:access-point-network"
    device_class: signal_strength
    state_class: measurement
    id: wifi_signal_value
# ...shared code end
    
servo:
  - id: my_servo
    output: pwm_output
    # transition_length: 1s

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO4
    frequency: 50 Hz
    
switch:
  - platform: template
    name: "Spider Drop Switch"
    optimistic: true
    # lambda: |-
    #   if (id(some_binary_sensor).state) {
    #     return true;
    #   } else {
    #     return false;
    #   }
    turn_on_action:
      - servo.write:
          id: my_servo
          level: 30.0%
      - delay: 2s
      - servo.detach: my_servo
    turn_off_action:
      - servo.write:
          id: my_servo
          level: -100.0%
      - delay: 2s
      - servo.detach: my_servo

button:
  - platform: template
    name: Drop Spider
    id: spider_button_drop

    # # Optional variables:
    # icon: "mdi:emoticon-outline"
    on_press:
    - servo.write:
        id: my_servo
        level: 30.0%
    - delay: 2s
    - servo.detach: my_servo

  - platform: template
    name: Reset Spider
    id: spider_button_set

    # # Optional variables:
    # icon: "mdi:emoticon-outline"
    on_press:
    - servo.write:
        id: my_servo
        level: -100.0%
    - delay: 2s
    - servo.detach: my_servo