#***************************************************
# Ice Maker Controller
####################################################
# Config Header for Device
####################################################
substitutions:
  # Used by ESP Home
  device_name: icemaker
  # Used by ESP Home
  device_description: "Ice Maker Controller"
  # Prefix used by Wifi IP, RSSI etc
  upper_devicename: "Ice Maker"
  # Prefix used by main Inputs & Outputs
  short_devicename: "Ice Maker"
  ip: 192.168.2.40
  pass: "hxN#^fPPv5ZRy%7l"
  status_led: LED_RED
  platform: ESP8266
  board: huzzah

####################################################
# Shared code from all my projects
####################################################
esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ${platform}
  board: ${board}
  # comment: NOT IN USE

wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: $ip
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    
logger: # Enable logging

api: # Enable Home Assistant API
  password: $pass

ota: # Enable over the air updates
  password: $pass
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  
status_led:
  pin:
    number: ${status_led}
    # inverted: True # To save power with using a coil relay

####################################################
# Non-Shared Code (May contain shared code)
####################################################  
binary_sensor:
# Shared code beginning... 
  # Device avaliablity
  - platform: status  
    name: ${upper_devicename} Status
    device_class: connectivity
# ...shared code end

switch:
  - platform: gpio
    pin:
      number: GPIO12
      mode: OUTPUT
    id: ICE_MAKER_SWITCH
    restore_mode: RESTORE_DEFAULT_ON  
    name: "Ice Maker Switch"

# GND for dallas
  - platform: gpio
    pin:
      number: GPIO13
      mode: OUTPUT_OPEN_DRAIN
    restore_mode: ALWAYS_OFF  
    name: "Active Drain"

# fan:
#   - platform: binary
#     output: ICE_MAKER_SWITCH
#     name: "Ice Maker"

dallas:
  - pin: GPIO14


   
text_sensor:
# Shared code beginning... 
  # Wifi Data
  - platform: wifi_info  
    ip_address:
      name: ${upper_devicename} IP
      icon: "mdi:ip-network-outline"
    ssid:
      name: ${upper_devicename} SSID
      icon: "mdi:help-network-outline"
    bssid:
      name: ${upper_devicename} BSSID
      icon: "mdi:access-point-network"
# ...shared code end

sensor:
# Shared code beginning... 
  # Wifi signal strength
  - platform: wifi_signal
    name: ${upper_devicename} RSSI
    update_interval: 300s
    # icon: "mdi:access-point-network"
    device_class: signal_strength
    state_class: measurement
    id: wifi_signal_value
# ...shared code end
    
  - platform: dallas
    address: 0x93001414B455FF28
    name: "Ice Maker Water Temperature"
