############################################################
#
# RFLink Lights, renamed in customise.yaml
# For contoller:
# see https://github.com/Genestealer/Home-Assistant-RFLink-Gateway-ESP8266
#
# Remote types:
# - Maclean: MCE07GB Remote Control Sockets
# - Eurodomest: Energenie Wall Light Switch MIHO026
# - Ansluta: Ikea 2.4GHz Remote control (903.007.73)
# - RFCustom: Status RCS-K09 433MHz remote control socket
#
############################################################

# 433MHz Maclean Plug in sockets conected to lights
- platform: rflink
  automatic_add: false
  device_defaults:
    fire_event: true
    signal_repetitions: 5
  devices:
    Maclean_0d52_04:
      name: Library Light
    # Maclean_0d82_03:
    #   name: Lamp_2 # renamed in customise.yaml to 'Guest Bedroom Light'
    # Maclean_0d85_02:
    #   name: Christmas Guest Bedroom Star
    # Maclean_0d82_02:
    #   name: Christmas Living Room Star
#    Maclean_0d85_04:
#      name: Living Room Bookcase Light

# # Moved to MQTT 2023 09 30
# # 433MHz Energenie Lights
# - platform: rflink
#   automatic_add: false
#   device_defaults:
#     # For this Energenie wall light switch,
#     # Send TX command over and over agin, as it only seems to listen for them occasionally/
#     # More tried helps ensure one makes it.
#     signal_repetitions: 15
#   devices:
#     Eurodomest_0fca6c_00: # Energenie MIHO026
#       name: Lamp_3 # renamed in customise.yaml to 'Upstairs Hall Light'
#     # Eurodomest_0fca2c_00: # Energenie MIHO026 one gang light switch
#     #   name: 'Dining Room Light'
#     Eurodomest_02940f_00: # Energenie MIHO093 two gang light switch
#       name: "Downstairs Hall Light"
#     # Eurodomest_02940f_02: # Energenie MIHO093 two gang light switch
#     #   name: "Upstairs Hall Light" # Not used, Lamp_3 used in it's place
#     Eurodomest_02940f_03: # Energenie MIHO026 one gang light switch
#       name: "Living Room Ceiling Light"
#     Eurodomest_061e5d_00: # Energenie MIHO026 one gang light switch
#       name: "Guest Bedroom Ceiling Light"
#     Eurodomest_061e5d_01: # Energenie MIHO026 one gang light switch
#       name: "Bedroom Ceiling Light"

# 433MHz UK branded as Silvercrest 303937 switch range is 0 to 4 with 00 being all off.
#    To clear the memory, use 00 all off or the off of the one to remove after unplugging for 2 seconds
#    You need to use the remotes to "program" the sockets before RFLink will work with them.
- platform: rflink
  automatic_add: false
  device_defaults:
    signal_repetitions: 10
    # fire_event: true
  devices:
    Unitec_9573_01:
      name: Christmas Garden Lights
    Unitec_9573_02:
      name: Christmas Bedroom Star
    Unitec_9573_03:
      name: Christmas Tree Lights
    Unitec_9573_04:
      name: Christmas Library Star
    Unitec_42d7_01:
      name: Christmas Guest Bedroom Star
    Unitec_42d7_02:
      name: Christmas Living Room Star
# # 2022 No longer used as I've moved over to Ikea Tradfi
# # 2.4GHz Lights Ikea Ansluta
# - platform: rflink
#   device_defaults:
#     signal_repetitions: 5
#     fire_event: true
#   devices:
#     ansluta_ce30_0:
#       name: Kitchen Under Counter Lights
#       aliases: Ansluta_ce30_0
#       # type: hybrid # Ikea Ansluta have two brightness modes. Note hybrid is not compatible with signal repetition.

# # Workaround for dimming the Ikea Ansluta lgiths
# Moved to a script to turn them on first
# - platform: template
#   lights:
#     kitchen_lights:
#       friendly_name: "Kitchen Under Counter Lights 2"
#       turn_on:
#         service: light.turn_on
#         entity_id: light.kitchen_under_counter_lights
#       turn_off:
#         service: light.turn_off
#         entity_id: light.kitchen_under_counter_lights
#       set_level:
#         service: shell_command.rflink_dim_kitchen_lights

###############################################
# Energenie MIHO003 Hand Controller, scan capture
# Button   On Command                                   Off Command
# 1        Eurodomest;ID=02940f;SWITCH=00;CMD=ON;       Eurodomest;ID=02940f;SWITCH=00;CMD=OFF;
# 2        Eurodomest;ID=02940f;SWITCH=03;CMD=ON;       Eurodomest;ID=02940f;SWITCH=03;CMD=OFF;
# 3        Eurodomest;ID=02940f;SWITCH=02;CMD=ON;       Eurodomest;ID=02940f;SWITCH=02;CMD=OFF;
# 4        Eurodomest;ID=02940f;SWITCH=06;CMD=ALLOFF;   Eurodomest;ID=02940f;SWITCH=06;CMD=ALLON;
# ALL      Eurodomest;ID=02940f;SWITCH=01;CMD=ON;       Eurodomest;ID=02940f;SWITCH=01;CMD=OFF;
###############################################
#Saved Energenie remote control commands via RF-Link
#Eurodomest_0fca6c_00:
# Off: Decimal: 219454 (24Bit) Binary: 000000110101100100111110 Tri-State: not applicable PulseLength: 309 microseconds Protocol: 1
# OFF Raw data: 9588,280,924,280,928,276,928,276,924,284,924,280,928,868,336,868,348,264,932,868,344,264,940,864,340,860,348,264,936,268,944,852,348,260,944,260,944,860,344,856,352,852,352,852,352,852,360,252,952,

# on Decimal: 219455 (24Bit) Binary: 000000110101100100111111 Tri-State: not applicable PulseLength: 309 microseconds Protocol: 1
# ON Raw data: 9588,280,928,272,928,276,932,272,932,268,928,284,920,872,344,864,344,268,940,860,340,264,940,864,340,860,348,264,940,264,944,856,352,256,948,256,952,860,344,860,348,852,352,852,364,840,360,848,360,
