############################################################
#
# Time and Date
# Used for driving template sensors which need a heatbeat to
# update, in  place of Now()
# Also needed for kloggy/HA-Irrigation-Version2
#
############################################################

# Needed for kloggy/HA-Irrigation-Version2 https://github.com/kloggy/HA-Irrigation-Version2/blob/master/Pre-Requisites.md
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
