substitutions:

  # PMSX003 Air Sensor Settings
  sensor_update_interval: 31s  
  # If > 30 seconds, and  tx_pin is set in the UART configuration, the fan will be spun down between measurements.
  

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "of4zH*IxKw49yt@H"

ota:
  password: "of4zH*IxKw49yt@H"

wifi:
  ssid: "IoT_VLAN"
  password: "qPGOfpLKI2vRRcOPmLAU8FHC1un7T7R1"
  manual_ip:
    static_ip: 192.168.2.42
    gateway: 192.168.2.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testair Fallback Hotspot"
    password: "CYzabELq2wpw"

captive_portal:

esphome:
  name: testair

esp8266:
  board: nodemcuv2

# Serial for pmsx003
uart:
  rx_pin: D4 # Share pin with ESP8266 onboard blue LED, so the LED flashes to show data traffic
  tx_pin: D3
  baud_rate: 9600

sensor:
  - platform: pmsx003 # Air sensor # https://esphome.io/components/sensor/pmsx003.html
    type: PMS5003T
    update_interval: ${sensor_update_interval}

    temperature:
      name: "Temperature"
      device_class: temperature
      state_class: measurement
   
    humidity:
      name: "Humidity"
      device_class: humidity
      state_class: measurement
 

    pm_1_0:
      name: "PM <1.0µm conc"
      device_class: "pm1"
      state_class: "measurement"
    pm_2_5:
      name: "PM <2.5µm conc"
      device_class: "pm25"
      state_class: "measurement"
    pm_10_0:
      name: "PM <10.0µm conc"
      device_class: pm10
      state_class: measurement

    pm_0_3um:
      name: "PM <0.3um in 0.1L of air"
    pm_0_5um:
      name: "PM <0.5um in 0.1L of air"
    pm_1_0um:
      name: "PM <1.0um in 0.1L of air"
    pm_2_5um:
      name: "PM <2.5um in 0.1L of air"
    pm_5_0um:
      name: "PM <5.0um in 0.1L of air"
    pm_10_0um:
      name: "PM <10.0um in 0.1L of air"