##############################################################
# Richard Huish 2023
# https://github.com/genestealer/Home-Assistant-Configuration
# Indoor Air Quality Sensor #1
# 
# To save the longevity of the air quality sensor, we turn it 
# off and make only occasional reads.
##############################################################
# Config Header for Device
##############################################################
substitutions:
  # Names
  device_name: air-quality-sensor-1 
  friendly_name: "Air Quality Sensor 1"
  ui_comment: "Air Quality Sensor 1 - UPDATED" # Only shows in UI.
  
  #Wifi Settings
  ip: 192.168.2.42
  gateway: 192.168.2.1
  subnet: 255.255.255.0

  #Board Settings
  status_led: D0 # GPIO16 - NodeMCU on-board LED
  status_led_inverted: "false"
  platform: ESP8266
  board: nodemcuv2

  project_name: "genestealer.air-quality-sensor"
  project_version: "1.0.0"
  package_import_url: "github://genestealer/Home-Assistant-Configuration/esphome/air-quality-sensor-1.yaml"
  
  # PMSX003 Air Sensor Settings
  sensor_update_interval: 300000ms #5 mins  
  # If > 30 seconds, and  tx_pin is set in the UART configuration, the fan will be spun down between measurements.
  
##############################################################
# Import shared code
##############################################################

# Packages
packages:
  device_base: !include .device_base.yaml

esphome:
  project:
    name: ${project_name}
    version: ${project_version}

dashboard_import:
  package_import_url: ${package_import_url}
  import_full_config: false # or true

##############################################################
# Main Code
##############################################################

# Serial for pmsx003
uart:
  rx_pin: D4 # Share pin with ESP8266 onboard blue LED, so the LED flashes to show data traffic
  tx_pin: D3
  baud_rate: 9600

sensor:
  - platform: pmsx003 # Air sensor # https://esphome.io/components/sensor/pmsx003.html
    type: PMS5003T
    update_interval: ${sensor_update_interval}
    
    temperature:
      name: "Temperature"
      device_class: temperature
      state_class: measurement
   
    humidity:
      name: "Humidity"
      device_class: humidity
      state_class: measurement

    # formaldehyde:
    #   name: "Formaldehyde Concentration"
    #   device_class: volatile_organic_compounds
    #   state_class: measurement
    # pm_1_0_std:

    # pm_2_5_std:

    # pm_10_0_std:

    pm_1_0:
      name: "PM <1.0µm conc"
      device_class: "pm1"
      state_class: "measurement"
    pm_2_5:
      name: "PM <2.5µm conc"
      device_class: "pm25"
      state_class: "measurement"
    pm_10_0:
      name: "PM <10.0µm conc"
      device_class: pm10
      state_class: measurement

    pm_0_3um:
      name: "PM <0.3um in 0.1L of air"
    pm_0_5um:
      name: "PM <0.5um in 0.1L of air"
    pm_1_0um:
      name: "PM <1.0um in 0.1L of air"
    pm_2_5um:
      name: "PM <2.5um in 0.1L of air"
    pm_5_0um:
      name: "PM <5.0um in 0.1L of air"
    pm_10_0um:
      name: "PM <10.0um in 0.1L of air"
    
