# ESP Home
esphome:
  name: ${name}
  comment: ${ui_comment}
  platform: ${platform}
  board: ${board}
  # build_path: ./build/${name}
  # Friendly names are used where appropriate in Home Assistant
  friendly_name: "${friendly_name}"
  # # Automatically add the mac address to the name
  # # so you can use a single firmware for all devices
  # name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

# Enable logging
logger:
  # level: ${log_level}

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_encryption_key
  reboot_timeout: 1h
# Enable over the air updates
ota:
  password: !secret esphome_ota_pass
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

# Wifi Details
wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: $ip
    gateway: $gateway
    subnet: $subnet

# Status LED for connection
status_led:
  pin:
    number: ${status_led}
    inverted: ${status_led_inverted}



##################################
# Buttons
##################################
# The restart button restarts the node remotely through Home Assistant.
button:
  - platform: restart
    name: "Restart"
    device_class: Restart


##################################
# Binary Sensors
##################################
binary_sensor:
  # Device avaliablity
  - platform: status
    name: Status
    device_class: connectivity

##################################
# Text Sensors
##################################
text_sensor:
  # Wifi Data
  - platform: wifi_info
    ip_address:
      name: IP
      icon: "mdi:ip-network-outline"
    mac_address:
      name: MAC
      icon: "mdi:access-point-network"
    ssid:
      name: SSID
      icon: "mdi:help-network-outline"
    bssid:
      name: BSSID
      icon: "mdi:access-point-network"

##################################
# Sensors
##################################
sensor:
  # Up-time
  - platform: uptime  
    name: Uptime  
    update_interval: 5min
    state_class: measurement
    device_class: duration

  # Wifi signal strength
  - platform: wifi_signal
    name: RSSI
    update_interval: 300s
    device_class: signal_strength
    state_class: measurement
  # filters:  
  #   - median:  
  #  window_size: 7  
  #  send_every: 4  
  #  send_first_at: 3


# sensor:
#   - <<: !include common/sensor/uptime.config.yaml
#   - <<: !include common/sensor/wifi_signal.config.yaml
# binary_sensor:
#   - <<: !include common/binary_sensor/connection_status.config.yaml

# switch:
#   - <<: !include common/switch/restart_switch.config.yaml


