##############################################################
# Richard Huish 2023
# https://github.com/genestealer/Home-Assistant-Configuration
# Indoor Bunny House Sensors
##############################################################
# Config Header for Device
##############################################################
substitutions:
  # Names
  name: indoor-bunny-house
  friendly_name: "Indoor Bunny House Sensors"
  ui_comment: "Indoor Bunny House Sensors - UPDATED" # Only shows in UI.
  
  #Wifi Settings
  ip: 192.168.2.37
  gateway: 192.168.2.1
  subnet: 255.255.255.0

  #Board Settings
  status_led: D0 # GPIO16 - NodeMCU on-board LED
  status_led_inverted: "false"
  platform: ESP8266
  board: nodemcuv2

  project_name: "genestealer.indoor-bunny-house-sensors"
  project_version: "1.0.0"
  package_import_url: "github://genestealer/Home-Assistant-Configuration/esphome/indoor-bunny-house-sensors.yaml"
  

##############################################################
# Import shared code
##############################################################

# Packages
packages:
  device_base: !include device_base.yaml

esphome:

dashboard_import:
  package_import_url: ${package_import_url}
  import_full_config: false # or true

##############################################################
# Main Code
##############################################################

sensor:
# Air Temperature and Humidity Sensor
  - platform: dht
    pin: D4 # GPIO2, pulled up - connected to on-board LED, boot fails if pulled LOW.
    temperature:
      name: Temperature
      state_class: measurement
      device_class: temperature
    humidity:
      name: Humidity
      state_class: measurement
      device_class: humidity
    update_interval: 300s
    model: DHT22

