homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: hee5aeseth8ke9eeZaepheeloWiezeefax6xa2LapaQuaezoh4zi0vohthieGoor
serial:
  port: tcp://192.168.10.35:8080
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: 15
  log_level: info
device_options:
  legacy: false
devices:
  '0x000b57fffe13967e':
    friendly_name: '0x000b57fffe13967e'
  '0x000d6ffffea20000':
    friendly_name: '0x000d6ffffea20000'
  '0x000b57fffe38a445':
    friendly_name: '0x000b57fffe38a445'
  '0x000d6ffffe9c3ea8':
    friendly_name: '0x000d6ffffe9c3ea8'
  '0x588e81fffe787201':
    friendly_name: Spare
  '0x60a423fffef24b3b':
    friendly_name: Motion 4b3b
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0x60a423fffece99ad':
    friendly_name: Motion 99ad
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0x60a423fffef26f3c':
    friendly_name: Motion 6f3c
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0xb4e3f9fffef34402':
    friendly_name: Office Remote
  '0xd0cf5efffec7e1fb':
    friendly_name: Office Cabinets Inside
  '0x588e81fffe6c99fd':
    friendly_name: Office Cabinets Front
    homeassistant:
      name: Office Cabinets Front
    legacy: false
    optimistic: true
  '0xbc33acfffe3025ec':
    friendly_name: Kitchen Under Counter
  '0x842e14fffe7f1823':
    friendly_name: Kitchen Counter
  '0x588e81fffe76d0ad':
    friendly_name: Kitchen Cabinet
  '0x804b50fffeef7a46':
    friendly_name: Kitchen Lights Remote
    legacy: false
  '0x000b57fffe9bad09':
    friendly_name: Kitchen Motion Sensor 1
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0x000b57fffe8edae5':
    friendly_name: Kitchen Motion Sensor 2
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0xbc33acfffebd4750':
    friendly_name: Office Lamp
    transition: 0
  '0x000b57fffe978d3f':
    friendly_name: Dining Room Lamp Left
  '0x000b57fffe51eb27':
    friendly_name: Dining Room 2
  '0x000b57fffeb829ec':
    friendly_name: Dining Room 3
  '0x000b57fffebdce17':
    friendly_name: Dining Room 1
  '0x000b57fffebfd68d':
    friendly_name: Dining Room 4
  '0xec1bbdfffe9eed51':
    friendly_name: Dining Room Remote
availability: true
groups:
  '1':
    friendly_name: Kitchen Lights
    devices:
      - 0x588e81fffe76d0ad/1
      - 0x842e14fffe7f1823/1
      - 0xbc33acfffe3025ec/1
  '2':
    friendly_name: Office Lights
    devices:
      - 0x588e81fffe6c99fd/1
      - 0xd0cf5efffec7e1fb/1
      - 0xbc33acfffebd4750/1
  '3':
    friendly_name: Dining Room Lights
    devices:
      - 0x000b57fffebdce17/1
      - 0x000b57fffe51eb27/1
      - 0x000b57fffeb829ec/1
      - 0x000b57fffebfd68d/1
      - 0x000b57fffe978d3f/1
