homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: hee5aeseth8ke9eeZaepheeloWiezeefax6xa2LapaQuaezoh4zi0vohthieGoor
serial:
  port: tcp://192.168.10.35:8080
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  channel: 15
  log_level: info
  last_seen: ISO_8601
device_options:
  legacy: false
devices:
  '0x000b57fffe13967e':
    friendly_name: '0x000b57fffe13967e'
  '0x000d6ffffea20000':
    friendly_name: '0x000d6ffffea20000'
    legacy: false
  '0x000b57fffe38a445':
    friendly_name: Test Remote
    legacy: false
  '0x000d6ffffe9c3ea8':
    friendly_name: '0x000d6ffffe9c3ea8'
    legacy: false
  '0x588e81fffe787201':
    friendly_name: Spare
  '0x60a423fffef24b3b':
    friendly_name: Motion 4b3b
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0x60a423fffece99ad':
    friendly_name: Hallway Motion Sensor 99ad
    occupancy_timeout: 90
    illuminance_below_threshold_check: true
  '0x60a423fffef26f3c':
    friendly_name: Kitchen Motion Sensor 3
    occupancy_timeout: 180
    illuminance_below_threshold_check: true
  '0xd0cf5efffec7e1fb':
    friendly_name: Office Cabinets Inside
  '0x588e81fffe6c99fd':
    friendly_name: Office Cabinets Front
    homeassistant:
      name: Office Cabinets Front
    legacy: false
    optimistic: true
  '0xbc33acfffe3025ec':
    friendly_name: Kitchen Under Counter
  '0x842e14fffe7f1823':
    friendly_name: Kitchen Counter
  '0x588e81fffe76d0ad':
    friendly_name: Kitchen Cabinet
  '0x804b50fffeef7a46':
    friendly_name: Kitchen Lights Remote
    legacy: false
  '0x000b57fffe9bad09':
    friendly_name: Kitchen Motion Sensor 1
    occupancy_timeout: 180
    illuminance_below_threshold_check: true
  '0x000b57fffe8edae5':
    friendly_name: Kitchen Motion Sensor 2
    occupancy_timeout: 180
    illuminance_below_threshold_check: true
  '0xbc33acfffebd4750':
    friendly_name: Office Lamp
    transition: 0
    state_action: true
  '0x000b57fffe978d3f':
    friendly_name: Dining Room Lamp Left
  '0x000b57fffe51eb27':
    friendly_name: Dining Room 2
    state_action: false
  '0x000b57fffeb829ec':
    friendly_name: Dining Room 3
  '0x000b57fffebdce17':
    friendly_name: Dining Room 1
  '0xec1bbdfffe9eed51':
    friendly_name: Dining Room Remote
    legacy: false
  '0xec1bbdfffedfbba3':
    friendly_name: Living Room Cabinets Front
  '0x000d6ffffec3aef6':
    friendly_name: Living Room Cabinets Inside
  '0xbc33acfffe9e1f16':
    friendly_name: Living Room Sofa Right
    state_action: true
  '0xbc33acfffea1e1c6':
    friendly_name: Living Room Sofa Left
    state_action: true
  '0xccccccfffe924b3c':
    friendly_name: Guest Bedroom Remote
    legacy: false
  '0x70ac08fffeee86c6':
    friendly_name: Guest Bedroom Lamp Left
  '0xbc33acfffea1daa2':
    friendly_name: Guest Bedroom Lamp Right
  '0xbc33acfffebcb527':
    friendly_name: Bedroom Lamp Left
  '0x000b57fffef3701e':
    friendly_name: Bedroom Remote
    legacy: false
  '0xbc33acfffe98c391':
    friendly_name: Bedroom Lamp Right
  '0xd0cf5efffed992d0':
    friendly_name: Repeater
  '0xb4e3f9fffef34402':
    friendly_name: Office Remote Control
    legacy: false
  '0x842e14fffe422e7a':
    friendly_name: Living Room Remote Control
    legacy: false
  '0xa4c1382cc73f5d09':
    friendly_name: Parcel Box
  '0x000b57fffeb19864':
    friendly_name: Outside 4 Down
  '0x000b57fffebf28bc':
    friendly_name: Outside 3 Up
  '0x000b57fffebefcf4':
    friendly_name: Outside 5 Down
  '0x000b57fffebed036':
    friendly_name: Outside 3 Down
  '0x000b57fffe520a0e':
    friendly_name: Outside 1 Up
  '0x000b57fffeaffb7b':
    friendly_name: Outside 4 Up
  '0x000b57fffebfd68d':
    friendly_name: Dining Room 4
    state_action: false
  '0x842e14fffe605be8':
    friendly_name: Outside 2 Down
  '0x000b57fffe8473b8':
    friendly_name: Outside 2 Up
  '0xa4c1383ed970356b':
    friendly_name: 'Garage Door Sensor '
  '0xa4c1387ab3af9d49':
    friendly_name: Back Door Sensor
  '0xa4c138fdb6272825':
    friendly_name: 'Front Door Sensor '
  '0x000b57fffe27203b':
    friendly_name: Dining Room Lamp Right
  '0x1c34f1fffe7b15b8':
    friendly_name: Office Wall Lamp
    state_action: true
  '0x6c5cb1fffe6730c8':
    friendly_name: '0x6c5cb1fffe6730c8'
  '0x60a423fffeadc632':
    friendly_name: 'Bedroom Bedside Remote '
    legacy: false
  '0x943469fffe5fb1a8':
    friendly_name: Outside 1 Down
    state_action: true
  '0x588e81fffe3ea2da':
    friendly_name: Kitchen Action Button
    legacy: false
  '0x680ae2fffe8125b0':
    friendly_name: '0x680ae2fffe8125b0'
    legacy: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
groups:
  '1':
    friendly_name: example_group
    devices:
      - 0x000b57fffebdce17/1
      - 0x000b57fffe51eb27/1
      - 0x000b57fffeb829ec/1
      - 0x000b57fffebfd68d/1
  '2':
    friendly_name: Dining Room Ceiling Lights
    devices:
      - 0x000b57fffebdce17/1
      - 0x000b57fffe51eb27/1
      - 0x000b57fffeb829ec/1
      - 0x000b57fffebfd68d/1
